module.exports = {
  content: ['./src/index.html', './src/**/*.html', './src/**/*.js'],
  css: ['./src/dist/style.css', './src/dist/mobile.css'],
  defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || [],
  safelist: [
    'is-open',
    'menu-open',
    'nav__toggle--active',
    'nav__list--active',
    'nav__link--active',
    /^header__/,
    /^content__/,
    /^hero__/,
    /^culture__/,
    /^footer__/,
    /^nav__/,
    /^btn/,
    /^page/,
    /^main/,
    /animation/,
    /keyframes/,
    /hover/,
    /focus/,
    /active/,
    /before/,
    /after/
  ],
};